"use client"
import { AuthProvider } from "@/app/lib/userAuth";
import React from 'react';
import { Inter } from 'next/font/google'
import './ui/globals.css'
import ApiClient from '@/app/lib/HttpRequestManager/api_client';

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Aba Incident Tracking',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {

  ApiClient.initialize('http://192.168.4.115:8181/api/v1'); 
  //console.log(ApiClient.getInstance());
  return (

    <html lang="en">
  <AuthProvider>
      <body className={inter.className}>
        {children}
        </body>
        </AuthProvider>
    </html>

  )
}
